version: 0.0
os: linux
files:
  - source: /
    destination: /tmp/pajaro-limon-frontend
hooks:
  ApplicationStart:
    - location: scripts/copy_client_files
      timeout: 300
      runas: ubuntu
    - location: scripts/restart_service
      timeout: 300
      runas: ubuntu
